### ISSUE TITLE
Dev env setup.

### ISSUE THREAD

**Issue by BhuvaneshwarBharathiya** [BhuvaneshwarBharathiya/Project20#8]
As a developer
I want to know how to set up development environment
So that, I can start writing code for common utility purpose.

AC:
1) simple help document that enable novice developer to start contributing to project.

**17-10-2020**
- Script to download JDK and Eclipse setup
[Readme](https://github.com/BhuvaneshwarBharathiya/Project20)

**Comment by sameernagegowda** [comment]
[P20_DevSetup.pptx](https://github.com/BhuvaneshwarBharathiya/Project20/files/5359135/P20_DevSetup.pptx)
